branches:
  - label: feature
    skip: false
    mode: immediate
    prefix: feature/
    autoLinkIssue: true
    autoCloseIssue: true
    autoDeleteBranch: true
    copyIssueDescriptionToPR: true
    copyIssueLabelsToPR: true
    copyIssueAssigneeToPR: true
    copyIssueProjectsToPR: true
  - label: hotfix
    skip: false
    mode: immediate
  - label: '*'
    skip: true
