- name: feature
  color: "1f6feb"
  description: "New feature or enhancement"

- name: hotfix
  color: "d73a4a"
  description: "Urgent production fix"

- name: misc
  color: "8b949e"
  description: "docs / other"
