name: CD
description: Continuos Deployment

inputs:
  base_folder_name: { required: true, description: "" }
  full_folder_name: { required: true, description: "" }
  fid: { required: true, description: "" }
  version: { required: true, description: "" }
  pid: { required: true, description: "" }
  or_url: { required: true, description: "" }
  token: { required: true, description: "" }
  target_env: { required: true, description: "" }
  entry_point: { required: true, description: "" }

runs:
  using: composite
  steps:
    - name: Publishing
      shell: bash
      run: |
        PACKAGE_PATH=$(find output -name '*.nupkg' | head -n 1)
        echo "Package Path: $PACKAGE_PATH"
        echo "Publishing Package to Tenant Feed "

        response=$(curl  --location \
          --header "Authorization: Bearer ${{ inputs.token }}" \
          --form "file=@$PACKAGE_PATH" \
          "${{ inputs.or_url }}/odata/Processes/UiPath.Server.Configuration.OData.UploadPackage()"
        )
        echo "Publish Response: $response"


    - name: check release
      shell: bash
      run: |
        echo "checking release"
        body="$(mktemp)"
        trap 'rm -f "$body"' EXIT

        curl_rc=0
        status=$(
          curl -L -sS \
            --connect-timeout 10 --max-time 120 \
            --output "$body" \
            --write-out '%{http_code}' \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "Content-Type: application/json" \
            -H "X-UIPATH-FolderPath: ${{ inputs.full_folder_name }}" \
            "${{ inputs.or_url }}/odata/Releases?%24select=Id%2CProcessKey%2CName%2CProcessType&%24filter=ProcessKey%20eq%20%27${{ inputs.pid }}%27"
        ) || curl_rc=$?

        echo "Status Code: $status"
        echo "::group::Response body"
        if [[ -s "$body" ]] && command -v jq >/dev/null && jq -e . "$body" >/dev/null 2>&1; then
          jq -r . "$body"
        else
          cat "$body"
        fi
        echo "::endgroup::"

        id_found="$(jq -r '.value[0].Id // empty' "$body" 2>/dev/null || true)"
        echo "id_found=$id_found" >> "$GITHUB_ENV"
        if [ -n "$id_found" ]; then
          echo "Release Id found"
          echo "CREATE=false" >> "$GITHUB_ENV"
        else
          echo "Release Id NOT found"
          echo "CREATE=true" >> "$GITHUB_ENV"
        fi

        if [[ $curl_rc -ne 0 || ${status:-0} -ge 400 ]]; then
          exit 1
        fi



    - name: upgrade release
      if: env.CREATE != 'true'
      shell: bash
      run: |
        echo "ugrading release"
        body="$(mktemp)"
        trap 'rm -f "$body"' EXIT

        curl_rc=0
        status=$(
          curl -L -sS \
            --connect-timeout 10 --max-time 120 \
            --output "$body" \
            --write-out '%{http_code}' \
            -X POST \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "Content-Type: application/json" \
            -H "Content-Length: 0" \
            -H "X-UIPATH-FolderPath: ${{ inputs.full_folder_name }}" \
            "${{ inputs.or_url }}/odata/Releases(${{env.id_found}})/UiPath.Server.Configuration.OData.UpdateToLatestPackageVersion"
        ) || curl_rc=$?

        echo "Status Code: $status"
        echo "::group::Response body"
        if command -v jq >/dev/null; then jq -r . "$body" || cat "$body"; else cat "$body"; fi
        echo "::endgroup::"

        if [[ $curl_rc -ne 0 || ${status:-0} -ge 400 ]]; then
          exit 1
        fi




    - name: update release
      if: env.CREATE != 'true'
      shell: bash
      run: |
        echo "updating release"
        body="$(mktemp)"
        trap 'rm -f "$body"' EXIT

        curl_rc=0
        status=$(
          curl -L -sS \
            --connect-timeout 10 --max-time 120 \
            --output "$body" \
            --write-out '%{http_code}' \
            -X PATCH \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "Content-Type: application/json" \
            -H "X-UIPATH-FolderPath: ${{ inputs.full_folder_name }}" \
            --data-binary @- \
            "${{ inputs.or_url }}/odata/Releases(${{ env.id_found}})" <<'JSON'
        {
          "Name": "${{ inputs.pid }}",
          "ProcessKey": "${{ inputs.pid }}",
          "ProcessVersion": "${{ inputs.version }}",
          "EntryPointPath": "${{ inputs.entry_point }}",
          "Description": "https://github.com/${{ github.repository_owner }}/${{ github.repository }}"
        }
        JSON
        ) || curl_rc=$?

        echo "Status Code: $status"
        echo "::group::Response body"
        if command -v jq >/dev/null; then jq -r . "$body" || cat "$body"; else cat "$body"; fi
        echo "::endgroup::"

        if [[ $curl_rc -ne 0 || ${status:-0} -ge 400 ]]; then
          exit 1
        fi

    - name: create release
      if: env.CREATE == 'true'
      shell: bash
      run: |
        echo "creating release"
        body="$(mktemp)"
        trap 'rm -f "$body"' EXIT

        curl_rc=0
        status=$(
          curl -L -sS \
            --connect-timeout 10 --max-time 120 \
            --output "$body" \
            --write-out '%{http_code}' \
            -X POST \
            -H "Authorization: Bearer ${{ inputs.token }}" \
            -H "Content-Type: application/json" \
            -H "X-UIPATH-FolderPath: ${{ inputs.full_folder_name }}" \
            --data-binary @- \
            "${{ inputs.or_url }}/odata/Releases" <<'JSON'
        {
          "Name": "${{ inputs.pid }}",
          "ProcessKey": "${{ inputs.pid }}",
          "ProcessVersion": "${{ inputs.version }}",
          "EntryPointPath": "${{ inputs.entry_point }}",
          "Description": "Repo https://github.com/${{ github.repository_owner }}/${{ github.repository }}"
        }
        JSON
        ) || curl_rc=$?

        echo "Status Code: $status"
        echo "::group::Response body"
        if command -v jq >/dev/null; then jq -r . "$body" || cat "$body"; else cat "$body"; fi
        echo "::endgroup::"

        if [[ $curl_rc -ne 0 || ${status:-0} -ge 400 ]]; then
          exit 1
        fi
