name: "Format JUnit XML to HTML"
description: "Converts JUnit XML to HTML using junit2html (cross-OS; requires Python)"
inputs:
  xml_path:     { required: true,  description: "Path to JUnit XML (artifact)" }
  out_path:     { required: false, default: "./email/TestResults.html" , description: "path to results"}
outputs:
  html:
    description: "HTML string"
    value: ${{ steps.embed_report.outputs.html }}
  out_path:
    description: "Path to the generated HTML file"
    value: ${{ steps.embed_report.outputs.out_path }}

runs:
  using: "composite"
  steps:
    - name: Ensure output dir
      shell: bash
      run: mkdir -p "$(dirname '${{ inputs.out_path }}')"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
              python-version: '3.x'

    - name: Generate Report from xml
      id: embed_report
      shell: bash
      run: |
        set -euo pipefail
        pip install --no-input junit2html
        xml="${{ inputs.xml_path }}"
        out="${{ inputs.out_path }}"


        mkdir -p "$(dirname "$out")"
        echo "xml: $xml out: $out"
        junit2html "$xml" "$out"
        sed -i 's/Generated by junit2html//g' "$out"
        html=$(cat $out)
        delimiter="HTML_CONTENT_$(cat /proc/sys/kernel/random/uuid)"
        {
          echo "html<<$delimiter"
          echo "$html"
          echo "$delimiter"
        } >> "$GITHUB_OUTPUT"




