name: "Format JUnit XML to HTML"
description: "Converts JUnit XML to HTML using junit2html (cross-OS; requires Python)"
inputs:
  xml_path:     { required: true,  description: "Path to JUnit XML (artifact)" }
  out_path:     { required: false, default: "./email/TestResults.html" , description: "path to results"}
outputs:
  html:
    description: "HTML string"
    value: ${{ steps.embed_report.outputs.html }}
  out_path:
    description: "Path to the generated HTML file"
    value: ${{ steps.embed_report.outputs.out_path }}

runs:
  using: "composite"
  steps:
    - name: Ensure output dir
      shell: bash
      run: mkdir -p "$(dirname '${{ inputs.out_path }}')"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
              python-version: '3.x'
    - name: Generate Report from XML
      id: embed_report
      shell: bash
      run: |
        set -euo pipefail
        python3 -m pip install --no-input --quiet junit2html

        xml="${{ inputs.xml_path }}"
        out="${{ inputs.out_path }}"

        mkdir -p "$(dirname "$out")"
        echo "xml: $xml out: $out"
        junit2html "$xml" "$out"

        # Optional: remove footer
        perl -0777 -pe 's/Generated by junit2html\s*//g' -i -- "$out"

        # Outputs: file path
        echo "out_path=$out" >> "$GITHUB_OUTPUT"

        # Outputs: raw HTML (multiline-safe, delimiter on its own line)
        delim="HTML_$(uuidgen 2>/dev/null || cat /proc/sys/kernel/random/uuid)"
        {
          echo "html<<$delim"
          cat "$out"
          printf '\n%s\n' "$delim"
        } >> "$GITHUB_OUTPUT"



              
    - name: html preview (debug)
      shell: bash
      run: |
        echo "Wrote: ${{ steps.embed_report.outputs.out_path }}"
        head -n 20 "${{ steps.embed_report.outputs.out_path }}" || true
        ls -l "${{ steps.embed_report.outputs.out_path }}" || true

