name: "Format JUnit XML to HTML"
description: "Converts JUnit XML to HTML using junit2html (cross-OS; requires Python)"
inputs:
  xml_path:     { required: true,  description: "Path to JUnit XML (artifact)" }
  out_path:     { required: false, default: "./email/TestResults.html" , description: "path to results"}
outputs:
  html:
    description: "HTML string"
    value: ${{ steps.read.outputs.html }}
  html_path:
    description: "Path written to"
    value: ${{ steps.read.outputs.html_path }}
runs:
  using: "composite"
  steps:
    - name: Ensure output dir
      shell: bash
      run: mkdir -p "$(dirname '${{ inputs.out_path }}')"

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Convert XML -> HTML
      shell: bash
      run: |
        python -m pip install --upgrade pip junit2html
        python - <<'PY'
        import sys, subprocess
        xml='${{ inputs.xml_path }}'
        out='${{ inputs.out_path }}'
        subprocess.check_call([sys.executable,'-m','junit2html',xml,out])
        PY

    - name: Strip footer text
      uses: actions/github-script@v7
      env:
        OUT: ${{ inputs.out_path }}
      with:
        script: |
          const fs = require('node:fs');
          const p = process.env.OUT;
          let t = fs.readFileSync(p,'utf8');
          t = t.replace('Generated by junit2html','');
          fs.writeFileSync(p,t);

    - id: read
      uses: actions/github-script@v7
      env:
        OUT: ${{ inputs.out_path }}
      with:
        script: |
          const fs = require('node:fs');
          const p = process.env.OUT;
          const html = fs.readFileSync(p,'utf8');
          core.setOutput('html', html);
          core.setOutput('html_path', p);
