name: Migrate Assets (placeholder)
description: No-op migration that validates manifest exists and echoes counts

runs:
  using: composite
  steps:
    - name: Parse AssetName values from XAML
      id: parse
      shell: bash
      run: |
          set -euo pipefail
          # Pattern matches AssetName=
          pattern='AssetName\s*=\s*["'"'"'][^"'"'"'<>]+["'"'"']'

          # Recursively search all *.xaml files, extract only values, deduplicate
          grep -r --include='*.xaml' -hPo "$pattern" . \
            | sed -E 's/.*AssetName\s*=\s*["'"'"']([^"'"'"'<>]+)["'"'"'].*/\1/' \
            | sort -u > assets.txt || true

          echo "Found $(wc -l < assets.txt) unique asset name(s):"
          cat assets.txt
          {
            echo "assets<<EOF"
            cat assets.txt
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

    - name: Upload asset list artifact
      uses: actions/upload-artifact@v4
      with:
          name: assets
          path: assets.txt
