name: Create branch for labeled issues
on:
  issues:
    types: [opened,assigned]

permissions:
  write-all

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:

      - name: Check if issue has assignees
        id: check
        if: github.event.action == 'opened'
        run: |
                if [ "${{ toJson(github.event.issue.assignees) }}" = "[]" ]; then
                  echo "Issue has no assignees."
                  echo "has_assignees=false" >> $GITHUB_OUTPUT
                else
                  echo "Issue has assignees."
                  echo "has_assignees=true" >> $GITHUB_OUTPUT
                fi


      - name: Auto-assign on open
        if: ${{ github.event.action == 'opened' }}
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.addAssignees({
              ...context.repo,
              issue_number: context.issue.number,
              assignees: [context.actor]
            });


      - name: Create Issue Branch
        if: github.event.action == 'assigned'
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
