name: Release - Process 2
description: Start the Release Process (fields used by CI and Change Request automation)
title: "Release: <short summary>"
labels:
  - release
  - process

body:
  # --- Top essentials --------------------------------------------------------
  - type: input
    id: requester_email
    attributes:
      label: Requester email
      description: We'll use this to contact you about this change.
      placeholder: "email@noreply.com"
    validations:
      required: true

  - type: input
    id: target_end_date
    attributes:
      label: Target end date
      description: "When should this be completed? Use YYYY-MM-DD."
      placeholder: "YYYY-MM-DD"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Overview
        Provide context up front so reviewers can quickly understand the change.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Put as much detail as possible about the change.
      placeholder: >
        What is changing? Why now? Scope, systems, dependencies, risks, milestones…
    validations:
      required: true

  - type: input
    id: business_value
    attributes:
      label: Business value (executive summary)
      description: "Business-speak version of the update: benefits, outcomes, KPIs."
      placeholder: "E.g., Reduces processing time by 30%, enables compliance with X, improves NPS."
    validations:
      required: true

  - type: input
    id: implementation_plan
    attributes:
      label: Implementation plan
      placeholder: "High-level steps, owners, sequence."
    validations:
      required: true

  - type: input
    id: backout_plan
    attributes:
      label: Backout plan
      placeholder: "How to revert if needed; triggers and steps."
    validations:
      required: true

  - type: input
    id: validation_plan
    attributes:
      label: Validation plan
      placeholder: "Pre/post checks, success criteria, monitoring, sign-off."
    validations:
      required: true

  # --- Audience & contacts ----------------------------------------------------
  - type: markdown
    attributes:
      value: |
        ## Audience & Contacts
        _Who is impacted and how they were told._

  - type: input
    id: backup_contact
    attributes:
      label: Backup contact (email)
      placeholder: "email@noreply.com"

  - type: input
    id: impacted_groups
    attributes:
      label: Impacted groups
      placeholder: "Group name(s)"
    validations:
      required: true

  - type: input
    id: impacted_users_emails
    attributes:
      label: Impacted users (emails)
      placeholder: "email@noreply.com"
    validations:
      required: true

  - type: input
    id: last_notified_when
    attributes:
      label: When were impacted users last notified?
      placeholder: "MM/DD/YY"
    validations:
      required: true

  - type: dropdown
    id: last_notified_how
    attributes:
      label: How were impacted users last notified?
      options:
        - Meeting
        - Teams message
        - Email
        - Call
        - In Person
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Effort/Project
      options:
        - Defect Resolution
        - Executive Sponsor Projects
        - Maintenance and Operation
        - Legislative Mandate
        - User Request
        - Test Environment
    validations:
      required: true

  # --- Confirmations (keep at bottom) ----------------------------------------
  - type: checkboxes
    id: checklist
    attributes:
      label: Confirmations
      description: Please check any that apply.
      options:
        - label: Impacts the public.
          required: false
        - label: Involves CDT.
          required: false
        - label: New app (ESD needs to know).
          required: false
