name: CI
description: Continuos Integration

inputs:
  folder_name: { required: true, description: "" }
  publishable: { required: true, description: "" }
  org: { required: true, description: "" }
  scopes: { required: true, description: "" }
  app_secret: { required: true, description: "" }
  app_id: { required: true, description: "" }
  or_url: { required: true, description: "" }
  target_env: { required: true, description: "" }
  tenant: { required: true, description: "" }

runs:
  using: composite
  steps:
    - name: Create Results DIR
      shell: powershell
      run: New-Item -Path "./results" -ItemType Directory

    - name: analyze
      if: inputs.target_env == 'dev'
      shell: powershell
      env:
        UIPATH_CLIENT_ID: ${{ inputs.app_id }}
        UIPATH_CLIENT_SECRET: ${{ inputs.app_secret }}
        UIPATH_ACCOUNT_NAME: ${{ inputs.org }}
        UIPATH_TENANT_NAME: ${{ inputs.tenant }}
        UIPATH_ORCHESTRATOR_URL: ${{ inputs.or_url }}
        UIPATH_SCOPES: "${{ inputs.scopes }}"
      run: ./uipath studio package analyze --source "${{ github.workspace }}/project.json" --query "violations[?severity == 'Warning' || severity == 'Error' ].[workflowDisplayName, description, recommendation]" --stop-on-rule-violation false   --profile target > ./results/analyze.json

    - name: run test cases
      shell: powershell
      if: inputs.publishable == 'true' && inputs.target_env == 'test'
      env:
        UIPATH_CLIENT_ID: ${{ inputs.app_id }}
        UIPATH_CLIENT_SECRET: ${{ inputs.app_secret }}
        UIPATH_ACCOUNT_NAME: ${{ inputs.org }}
        UIPATH_TENANT_NAME: ${{ inputs.tenant }}
        UIPATH_ORCHESTRATOR_URL: ${{ inputs.or_url }}
        UIPATH_SCOPES: "${{ inputs.scopes }}"
      run: |
        $output = ./uipath studio test run --source "${{ github.workspace }}/project.json" --folder "${{ inputs.folder_name }}" --results-output "junit" --debug --profile target
        echo $output
        echo $output > "./results/TestResults.xml"

    - name: Upload artifact
      if: (inputs.publishable == 'true' && inputs.target_env == 'test') || inputs.target_env == 'dev'
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: ./results/*

