name: Pipeline Caller

on:
  push:
    branches:
      - $default-branch
      - 'feature/**'
      - 'hotfix/**'

    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - $default-branch
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  write-all

jobs:


  pre-check:
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.check.outputs.target_env }}
      source_ref: ${{ steps.check.outputs.source_ref }}
      skip: ${{ steps.check.outputs.check }}
    steps:
      - name: set target_env and decide skip
        id: check
        uses: dhillon-shawn/Local-Uipath-CICD/.github/actions/pre-check@main

  pipeline:
    needs: pre-check
    if: ${{ needs.pre-check.outputs.skip != 'true' }}
    uses: dhillon-shawn/Local-Uipath-CICD/.github/workflows/pipeline.yml@main
    secrets: inherit
    with:
      target_env: ${{ needs.pre-check.outputs.target_env }}
      source_ref: ${{ needs.pre-check.outputs.source_ref }}
