name: Pipeline Caller

on:
  push:
    branches:
      - $default-branch
      - 'feature/**'
      - 'hotfix/**'

    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - $default-branch
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  write-all

jobs:


  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Decide env
        id: decide
        uses: dhillon-shawn/Local-Uipath-CICD/.github/actions/pipeline-prep@main

      - name: Call pipeline
        if: ${{ steps.decide.outputs.skip != 'true' }}
        uses: dhillon-shawn/Local-Uipath-CICD/.github/workflows/pipeline.yml@main
        secrets: inherit
        with:
          target_env: ${{ steps.decide.outputs.target_env }}
          source_ref: ${{ steps.decide.outputs.source_ref }}
