name: AWS TEST

on:
  workflow_dispatch:

permissions:
      write-all

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
              - name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v4
                with:
                        role-to-assume: ${{ secrets.RPA_UIPATH_CICD_ROLE_ARN }}
                        aws-region: "us-west-2"
                        role-session-name: GitHubActions-${{ github.run_id }}

              - name: Get secrets from AWS Secrets Manager
                uses: aws-actions/aws-secretsmanager-get-secrets@v1
                with:
                        secret-ids: |
                            ENV, ${{ secrets.RPA_UIPATH_CICD_SECRET_ARN }}
                        parse-json-secrets: true

              - name: Echo all environment variables
                run: env
