name: AWS TEST

on:
  workflow_dispatch:
  workflow_call:
  push:

permissions:
    write-all

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:

          - uses: actions/checkout@v4
          - name: get
            uses: ./.github/actions/aws
            with:
                env: "DEV"
                role_arn: ${{ secrets.RPA_UIPATH_CICD_ROLE_ARN }}
                aws_region: "us-west-2"
                secret_id: ${{ secrets.RPA_UIPATH_CICD_SECRET_ARN }}



          - name: Dump vars context
            env:
                VARS_JSON: ${{ toJSON(vars) }}
            run: echo "${VARS_JSON}"

          - name: Dump env context
            env:
                ENV_JSON: ${{ toJSON(env) }}
            run: echo "${ENV_JSON}"

          - name: Use resolved vars
            run: echo "APP_ID and APP_SECRET are available (masked)."
