name: Issue → Branch + PR

on:
  workflow_call:

permissions:
  write-all

concurrency:
  group: issue-${{ github.event.issue.number }}
  cancel-in-progress: false


jobs:

  parse:
    if: >
      contains(join(github.event.issue.labels.*.name, ','), 'release') ||
      contains(join(github.event.issue.labels.*.name, ','), 'hotfix')
    runs-on: ubuntu-latest
    steps:
      - name: assign check
        id: check
        run: |
          echo "issue_number=${{ github.event.issue.number }}"
          echo "assignees_json=${{ toJson(github.event.issue.assignees) }}"
          if [ "${{ toJson(github.event.issue.assignees) }}" = "[]" ]; then
            echo "has_assignees=false" >> $GITHUB_OUTPUT
            echo "result=no current assignee"
          else
            echo "has_assignees=true" >> $GITHUB_OUTPUT
            echo "result=already assigned"
          fi

      - name: assign ensure
        if: steps.check.outputs.has_assignees == 'false'
        uses: pozil/auto-assign-issue@v2
        with:
          assignees: "${{ github.event.issue.user.login }}"
          numOfAssignee: 1

      - name: issue refresh assignee
        id: issue
        uses: actions/github-script@v7
        with:
          script: |
            const repo = context.repo;
            const num = context.payload.issue.number;
            const { data: issue } = await github.rest.issues.get({ ...repo, issue_number: num });
            core.setOutput('assignees', JSON.stringify((issue.assignees || []).map(a => a.login)));



            
      - name: Create branch + empty commit + PR, then comment (API-only, idempotent)
        uses: actions/github-script@v7
        with:
          script: |
            const repo = context.repo;
            const issue = context.payload.issue;
            const labels = issue.labels.map(l => typeof l === 'string' ? l : l.name);
            const has = (n) => labels.includes(n);

            // Decide type (priority hotfix > library > process)
            let type = null, prefix = null, draft = null;
            if (has('hotfix'))      { type = 'hotfix';  prefix = 'hotfix';  draft = false; }
            else if (has('library')){ type = 'library'; prefix = 'library'; draft = true;  }
            else if (has('process')){ type = 'process'; prefix = 'release'; draft = true;  }
            else { return; } // quietly exit if not one of the three

            // Branch name: <prefix>/<issue-number>-<slug>  (e.g., library/8-fix-x)
            const slug = (issue.title || '')
              .toLowerCase()
              .replace(/[^a-z0-9]+/g, '-')
              .replace(/^-+|-+$/g, '')
              .replace(/-+/g, '-');
            const branch = `${prefix}/${issue.number}-${slug}`;

            // Resolve base (default) branch SHA
            const defaultBranch = context.payload.repository.default_branch;
            const { data: baseRef } = await github.rest.git.getRef({ ...repo, ref: `heads/${defaultBranch}` });
            const baseSha = baseRef.object.sha;

            // Ensure branch exists (idempotent)
            let branchSha;
            try {
              const r = await github.rest.git.getRef({ ...repo, ref: `heads/${branch}` });
              branchSha = r.data.object.sha;
            } catch {
              await github.rest.git.createRef({ ...repo, ref: `refs/heads/${branch}`, sha: baseSha });
              branchSha = baseSha;
            }

            // Ensure an empty commit exists on the branch (so a PR can be opened cleanly)
            const initMsg = `chore(${type}): initialize (#${issue.number})`;
            try {
              const head = await github.rest.repos.listCommits({ ...repo, sha: branch, per_page: 1 });
              const hasInit = head.data[0] && head.data[0].commit.message === initMsg;
              if (!hasInit) {
                const { data: headCommit } = await github.rest.git.getCommit({ ...repo, commit_sha: branchSha });
                const { data: newCommit } = await github.rest.git.createCommit({
                  ...repo, message: initMsg, tree: headCommit.tree.sha, parents: [branchSha]
                });
                await github.rest.git.updateRef({ ...repo, ref: `heads/${branch}`, sha: newCommit.sha, force: false });
              }
            } catch { /* noop */ }

            // Find or create PR (link with auto-close keyword)
            const prTitle = `${issue.title} (#${issue.number})`;
            const prBody = [
              `Closes #${issue.number}`,  // <-- ensures link + auto-close on merge
              `Type: ${type}`,
              '',
              '---',
              '',
              issue.body || ''
            ].join('\n');
            const headRef = `${repo.owner}:${branch}`;
            let { data: prs } = await github.rest.pulls.list({ ...repo, state: 'open', head: headRef });
            let pr = prs[0];
            if (!pr) {
              const created = await github.rest.pulls.create({
                ...repo, title: prTitle, head: branch, base: defaultBranch, body: prBody, draft
              });
              pr = created.data;
            } else if (!(pr.body || '').includes(`Closes #${issue.number}`)) {
              await github.rest.pulls.update({ ...repo, pull_number: pr.number, body: prBody });
            }

            // Copy assignees from issue → PR (PRs are issues under the hood)
            const assignees = (issue.assignees || []).map(a => a.login).filter(Boolean);
            if (assignees.length) {
              await github.rest.issues.addAssignees({
                ...repo, issue_number: pr.number, assignees
              }).catch(() => {});
            }

            // Comment back on the originating issue with meta
            const meta = {
              pr: pr.number,
              pr_url: pr.html_url,
              branch: pr.head.ref,
              base: pr.base.ref,
              issue: issue.number,
              source_head_sha: pr.head.sha,
              slug,
              created_by: context.actor,
              created_at: new Date().toISOString()
            };
            const commentBody = [
              `Opened PR: ${pr.html_url}`,
              `Branch: \`${pr.head.ref}\``,
              '',
              '<!-- pr-meta:',
              JSON.stringify(meta),
              '-->'
            ].join('\n');

            // Post once per issue (avoid duplicates)
            const existing = await github.rest.issues.listComments({ ...repo, issue_number: issue.number, per_page: 50 });
            const already = existing.data.some(c => (c.body || '').includes(`"pr": ${pr.number}`) && (c.body || '').includes('<!-- pr-meta:'));
            if (!already) {
              await github.rest.issues.createComment({ ...repo, issue_number: issue.number, body: commentBody });
            }
