name: Link PR to issue & enable auto-merge
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    # target is the default branch (GitHub resolves this)
    branches:
      - $default-branch

permissions:
  contents: write
  pull-requests: write

jobs:
  link_and_automerge:
    if: startsWith(github.head_ref, 'feature/issue-') || startsWith(github.head_ref, 'hotfix/issue-')
    runs-on: ubuntu-latest
    steps:
      - name: Extract issue number from branch
        id: parse
        run: |
          BRANCH="${{ github.head_ref }}"
          if [[ "$BRANCH" =~ issue-([0-9]+) ]]; then
            echo "issue=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "Could not parse issue number from $BRANCH"; exit 1
          fi

      - name: Ensure PR body includes closing keyword
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = '${{ steps.parse.outputs.issue }}';
            const closing = `Closes #${issue}`;
            const pr = context.payload.pull_request;
            const body = pr.body || "";
            if (!body.includes(closing)) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                body: (body ? body + "\n\n" : "") + closing
              });
            }

      - name: Enable auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: SQUASH
