name: Revert latest merge
on: workflow_dispatch

permissions:
  contents: write

jobs:
  revert-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Revert most recent merge commit
        run: |
          set -euo pipefail
          MERGE_SHA=$(git rev-list --merges -n 1 HEAD || true)
          if [ -z "$MERGE_SHA" ]; then
            echo "No merge commits found on this branch."
            exit 1
          fi
          echo "Reverting merge $MERGE_SHA"
          git revert -m 1 --no-edit "$MERGE_SHA"
          git push origin HEAD
