name: format and send email
on:
  workflow_call:
    inputs:
      target_env: { type: string, required: true }
      email: { type: string, required: true }
      result: { type: string, required: true }
      version: { type: string, required: true }
      folder_name: { type: string, required: true }
      pid: { type: string, required: true }
      publishable: { type: string, required: false }
      migrate: { type: string, required: false }
    secrets: {}

jobs:


  format:
    runs-on: ubuntu-latest
    outputs:
      subject: ${{ steps.compose.outputs.subject }}
      html: ${{ steps.compose.outputs.html }}
    steps:

      - name: Compose Email
        uses: dhillon-shawn/Local-CICD-UTILS/format-email@v0
        id: compose
        with:
          target_env: ${{ inputs.target_env }}
          publishable: ${{ inputs.publishable }}
          json_path: results/analyze.json
          xml_path: results/test.xml
          cd_status: ${{ inputs.result }}
          source_ref: ${{ github.sha }}
          version: ${{ inputs.version }}
          folder_name: ${{ inputs.folder_name }}
          project_id: ${{ inputs.pid }}
          migrate: ${{ inputs.migrate }}


  send:
    runs-on: windows-latest
    needs: format
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
            name: email
            path: .


      - name: Send Email (SMTP)
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ needs.format.outputs.subject }}
          to: ${{ inputs.email }}
          from: "UiPath CI/CD <uipath-cicd@noreply.com>"
          html_body: file://${{ needs.format.outputs.html }}
          convert_markdown: false
