name: AWS TEST

on:
  workflow_dispatch:
  workflow_call:
  push:

permissions:
    write-all

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:

          - uses: actions/checkout@v4


          - name: get dev
            uses: ./.github/actions/auth
            with:
                env: "DEV"
                role_arn: ${{ secrets.RPA_UIPATH_CICD_ROLE_ARN }}
                aws_region: "us-west-2"
                secret_id: ${{ secrets.RPA_UIPATH_CICD_SECRET_ARN }}


          - name: Folder
            run: |
                response=$(curl -L -sS \
                --connect-timeout 10 --max-time 120 -w '\n%{http_code}' \
                --header "Authorization: Bearer $TOKEN" \
                "${{env.OR_URL}}/odata/Folders"
                )
                echo "Response: $response"
                curl_rc=$?
                
                if [[ $curl_rc -ne 0 ]]; then
                  exit 1
                fi
