name: TEST

on:
  workflow_dispatch:
  workflow_call:
  push:

permissions:
    write-all

env:
  scope: "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Monitoring OR.Robots.Read OR.Settings.Read OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Users.Read"

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:

          - uses: actions/checkout@v4


          - name: get dev
            uses: ./.github/actions/auth
            with:
                target_env: "dev"
                role_arn: ${{ secrets.RPA_UIPATH_CICD_ROLE_ARN }}
                aws_region: "us-west-2"
                secret_id: ${{ secrets.RPA_UIPATH_CICD_SECRET_ARN }}
                scopes: ${{env.scope}}


          - name: folders
            run: |
                body="$(mktemp)"
                trap 'rm -f "$body"' EXIT
                status=$(curl -L -sS \
                --connect-timeout 10 --max-time 120 \
                --output "$body" --write-out '%{http_code}' \
                --header "Authorization: Bearer $TOKEN" \
                "${{env.OR_URL}}/odata/Folders"
                ) || curl_rc=$?
                 
                echo "Status Code: $status"
                echo "::group::Response body"
                if command -v jq >/dev/null; then jq -r . "$body" || cat "$body"; else cat "$body"; fi
                echo "::endgroup::"

                if [[ $curl_rc -ne 0 || "$status" -ge 400 ]]; then
                  exit 1
                fi
                
          - name: releases
            run: |
                response=$(curl -L  \
                  --header "Authorization: Bearer $TOKEN" \
                  --header "X-UIPATH-FolderPath: t2" \
                  "${{env.OR_URL}}/odata/Releases"
                ) 
                echo "REPONSE $response"
          - name: release
            run: |
                body="$(mktemp)"
                trap 'rm -f "$body"' EXIT
                status=$(curl -L -sS \
                --connect-timeout 10 --max-time 120 \
                --output "$body" --write-out '%{http_code}' \
                --header "Authorization: Bearer $TOKEN" \
                --header "X-UIPATH-FolderPath: t2" \
                "${{env.OR_URL}}/odata/Releases"
                ) || curl_rc=$?
                 
                echo "Status Code: $status"
                echo "::group::Response body"
                if command -v jq >/dev/null; then jq -r . "$body" || cat "$body"; else cat "$body"; fi
                echo "::endgroup::"

                if [[ $curl_rc -ne 0 || "$status" -ge 400 ]]; then
                  exit 1
                fi
                
          - name: release
            run: |
                body="$(mktemp)"
                status=$(curl -L -sS \
                --connect-timeout 10 --max-time 120 \
                --output "$body" --write-out '%{http_code}' \
                --header "Authorization: Bearer $TOKEN" \
                --header "X-UIPATH-FolderPath: t2" \
                "${{env.OR_URL}}/odata/Releases"
                ) || curl_rc=$?
                 
                echo "Status Code: $status"
                echo "::group::Response body"
                jq -r . "$body" || cat "$body"
                echo "::endgroup::"

                if [[ $curl_rc -ne 0 || "$status" -ge 400 ]]; then
                  exit 1
                fi

          - name: release
            run: |
                body="$(mktemp)"
                status=$(curl -L -sS \
                --connect-timeout 10 --max-time 120 \
                --output "$body" --write-out '%{http_code}' \
                --header "Authorization: Bearer $TOKEN" \
                "${{env.OR_URL}}/odata/Releases"
                ) || curl_rc=$?
                 
                echo "Status Code: $status"
                echo "::group::Response body"
                jq -r . "$body" || cat "$body"
                echo "::endgroup::"

                if [[ $curl_rc -ne 0 || "$status" -ge 400 ]]; then
                  exit 1
                fi
                
  



