name: TEST

on:
  workflow_dispatch:
  workflow_call:
  push:

permissions:
    write-all

env:
  scope: "OR.Assets OR.BackgroundTasks OR.Execution OR.Folders OR.Jobs OR.Machines.Read OR.Monitoring OR.Robots.Read OR.Settings.Read OR.TestSets OR.TestSetExecutions OR.TestSetSchedules OR.Users.Read"

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:

          - uses: actions/checkout@v4


          - name: get dev
            uses: ./.github/actions/auth
            with:
                target_env: "dev"
                role_arn: ${{ secrets.RPA_UIPATH_CICD_ROLE_ARN }}
                aws_region: "us-west-2"
                secret_id: ${{ secrets.RPA_UIPATH_CICD_SECRET_ARN }}
                scopes: ${{env.scope}}





          - name: folders
            run: |
                body="$(mktemp)"
                
                status=$(curl -L -sS \
                --connect-timeout 10 --max-time 120 \
                --output "$body" --write-out '%{http_code}' \
                --header "Authorization: Bearer $TOKEN" \
                "${{env.OR_URL}}/odata/Folders"
                ) || curl_rc=$?
                 
                echo "Status Code: $status"
                echo "::group::Response body"
                jq -r . "$body" || cat "$body"
                echo "::endgroup::"

                if [[ $curl_rc -ne 0 || "$status" -ge 400 ]]; then
                  exit 1
                fi
                
                ls
                
          - name: folders
            run: |
                body="$(mktemp)"
                
                status=$(curl -L -sS \
                --connect-timeout 10 --max-time 120 \
                --output "$body" --write-out '%{http_code}' \
                --header "Authorization: Bearer $TOKEN" \
                "${{env.OR_URL}}/odata/Folders"
                ) || curl_rc=$?
                 
                echo "Status Code: $status"
                echo "::group::Response body"
                jq -r . "$body" || cat "$body"
                echo "::endgroup::"

                if [[ $curl_rc -ne 0 || "$status" -ge 400 ]]; then
                  exit 1
                fi
                
                ls
                rm -f "$body"
                ls

          - name: folders
            run: |
                body="$(mktemp)"
                
                status=$(curl -L -sS \
                --connect-timeout 10 --max-time 120 \
                --output "$body" --write-out '%{http_code}' \
                --header "Authorization: Bearer $TOKEN" \
                "${{env.OR_URL}}/odata/Folder"
                ) || curl_rc=$?
                 
                echo "Status Code: $status"
                echo "::group::Response body"
                jq -r . "$body" || cat "$body"
                echo "::endgroup::"

                if [[ $curl_rc -ne 0 || "$status" -ge 400]]; then
                  exit 1
                fi
                
                
                ls
